### ISSUE TITLE
Windy

### ISSUE THREAD

**Issue by hmreumann** [vemcogroup/laravel-weather#2]
Hallo, would it be possible to add Windy Api as a Weather Provider? I think it has forecast with the free api key, but it has to be rendered. Thanks in advance.

**Comment by eldor** [comment]
Hi @hmreumann as far as I can see the free version is not available for production:
**Development purpose only, not intended for production**

https://api.windy.com/point-forecast

**Comment by hmreumann** [comment]
Yes that is right, but the free version has forecast at least with some layers. The full versión has much more layers. It can be configured to show the map at a certain position and date. I think is very powerfull. In case the aplication might need the full version can pay for it.

**Comment by eldor** [comment]
Ok, I see your point and you are welcome to do a PR are with the new provider if you want?
We already have google geocoder implemented for you to convert address to geocodes.
