### ISSUE TITLE
Historical data requests forces interval to 1

### ISSUE THREAD

**Issue by diegocam** [vemcogroup/laravel-weather#4]
Hello. We started using this package recently and were attempting to create this URL for WeatherStack:
```
https://api.weatherstack.com/historical?query=25.7617,-80.1918&historical_date_start=2021-01-01&historical_date_end=2021-01-02&units=f&hourly=1&interval=24
```
As you can see we are trying to get historical data, with the interval set to `interval=24`. However when calling 
```php
weather()->getHistorical($request);
```
It forces the interval to change to `interval=1`. Seems to be coming from this line https://github.com/vemcogroup/laravel-weather/blob/master/src/Providers/Weatherstack.php#L53

Is there a way to override this somehow?

**Comment by eldor** [comment]
Hi @diegocam,

Thank you for the finding, and of course it should be configurable.
I have added it to config (See readme) and tag a new version:
https://github.com/vemcogroup/laravel-weather/releases/tag/2.0.3

Let me know if it fix it for you.

**Comment by diegocam** [comment]
Awesome. Thank you for prompt response.
